---
# These are aliases that define file names with group vars for a host.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `host_vars`.
machine_aliases:
  VirtualBox: vbox.yml

arch_root: /mnt

country: Austria
timezone: Europe/Vienna
locales:
  - en_US
  - uk_UA

user:
  name: roland
  group: roland
  uid: 1000
  comment: Roland Puntaier
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: roland.puntaier@gmail.com

extra_packages:
  # system
  - bat
  - fd
  - fzf
  - hardinfo
  - ripgrep
  - tldr
  - tmux
  - usbutils

  # network 
  - mtr
  - traceroute

  # filesystem
  - dosfstools
  - exfat-utils
  - ntfs-3g
  - tree

  # archives
  - file-roller
  - p7zip
  - unrar
  - unzip
  - zip

  # media
  - ardour
  - blender
  - calibre
  - chromium
  - digikam
  - gimp
  - goldendict
  - gpick
  - inkscape

  # misc
  - pass
  - libreoffice-still

  # spellcheck
  - vim-spell-en
  - vim-spell-ru
  - vim-spell-it
  - vim-spell-de
  - vim-spell-fr
  - vim-spell-es

  # development
  - clang
  - cloc
  - gdb
  - git
  - httpie
  - neovim
  - neovim-qt
  - python-pip
  - python-pynvim
  - python-jedi
  - code

extra_aur_packages:
  - waf-git
  - wordnet-cli
  - urxvt-vim-scrollback-git
  - powerline-console-fonts
  - cling-bin
  - erfa
  - python-astropy
  - github-cli

dotfiles:
  repo: "https://github.com/rpuntaie/dotfiles"
  dest: "${HOME}/.dotfiles"
  install_shell_cmds:
    - "./install"
  deps:
    - stow
    - xdg-user-dirs
