---
- name: clone dotfiles
  git:
    repo: "{{ dotfiles.repo }}"
    dest: "{{ dotfiles.dest }}"
  become: yes
  become_user: "{{ user.name }}"

- name: install dotfiles dependencies
  pacman:
    name: "{{ dotfiles.deps }}"

- name: install dotfiles
  shell: "{{ item }}"
  become_user: "{{ user.name }}"
  with_items: "{{ dotfiles.install_shell_cmds }}"
  args:
    chdir: "{{ dotfiles.dest }}"

