---
- name: configure systemd logind
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf

- name: install Gnome
  pacman:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
      - gendesk

- name: enable GDM
  systemd:
    name: gdm
    state: started
    enabled: yes

- name: install Gnome extensions
  aur:
    name:
      - gnome-shell-extension-gtktitlebar-git
      - gnome-shell-extension-topicons-plus
      - gnome-shell-extension-system-monitor-git
  become: yes
  become_user: "{{ user.name }}"

- name: create dconf database dir
  file:
    path: /etc/dconf/db/gnome.d
    state: directory
    recurse: yes

- name: create dconf profile dir
  file:
    path: /etc/dconf/profile
    state: directory
    recurse: yes

- name: configure dconf database
  copy:
    src: mygnome.conf
    dest: /etc/dconf/db/gnome.d/mygnome.conf
  notify: update dconf database

- name: configure dconf profile
  lineinfile:
    path: /etc/dconf/profile/user
    line: "{{ item }}"
    create: yes
  with_items:
    - "user-db:user"
    - "system-db:gnome"
  notify: update dconf database

- name: install GNOME Shell Extensions support
  pacman:
    name:
      - gnome-shell-extensions
      - chrome-gnome-shell


- import_tasks: wayland.yml
- import_tasks: bluetooth.yml
- import_tasks: themes.yml
- import_tasks: media.yml

- meta: flush_handlers
