hostname: vbox

guest_extra_packages:
  - virtualbox
  - virtualbox-guest-utils

host_extra_aur_packages: []

partition:

# Define storage partitioning layout.
# Required fields for partition:
#   - name
#   - start
#   - end
#   - encrypt
#
# Optional fields:
#   - flags
#   - filesystem
#   - mountpoint

  device: /dev/sda
  table: gpt
  partitions:

    - name: root
      filesystem: ext4
      start: 512MiB
      end: 100%
      encrypt: false
      mountpoint: /

    - name: efi
      filesystem: vfat
      start: 0%
      end: 512MiB
      encrypt: false
      flags: [boot]
      mountpoint: /boot
